server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/futsaldb
    username: futsaluser
    password: futsalpass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds

